Disciplina: **Mineração de Dados**

Professor: **Wilson Castello Branco Neto**

Aula 12 - Exemplo 1: Regras de Associação

Nome: Wilson Castello Branco Neto

Leitura e apresentação do dataset com os dados das transações realizadas.

Dataset disponível em: https://www.kaggle.com/datasets/lissetteg/ecommerce-dataset

In [3]:
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [16]:
df = pd.read_csv('/content/gdrive/MyDrive/Ciencia_de_dados2/Aula 12data.csv')

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

Exclusão de todas as colunas desnecessárias. São utilizadas apenas o código da transação (**InvoiceNo**) e o código do produto (**StockCode**).

Além disto, se algum registro tiver com um destes atributos vazios ele será excluído.

In [ ]:
df=df[["InvoiceNo","StockCode"]]
df.dropna(inplace=True)

df

/tmp/ipython-input-119615714.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

       InvoiceNo StockCode
0         536365    85123A
1         536365     71053
2         536365    84406B
3         536365    84029G
4         536365    84029E
...          ...       ...
541904    581587     22613
541905    581587     22899
541906    581587     23254
541907    581587     23255
541908    581587     22138

[541909 rows x 2 columns]

Agrupa os itens vendidos em cada transação em uma lista

In [ ]:
transacoes=df.groupby("InvoiceNo")["StockCode"].apply(list).reset_index(name='Items')

transacoes

      InvoiceNo                                              Items
0        536365  [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
1        536366                                     [22633, 22632]
2        536367  [84879, 22745, 22748, 22749, 22310, 84969, 226...
3        536368                       [22960, 22913, 22912, 22914]
4        536369                                            [21756]
...         ...                                                ...
25895   C581484                                            [23843]
25896   C581490                                     [22178, 23144]
25897   C581499                                                [M]
25898   C581568                                            [21258]
25899   C581569                                     [84978, 20979]

[25900 rows x 2 columns]

Cria uma lista de transacoes, sendo que em cada lista há uma sublista com os itens de cada transação. Apresenta as duas primeiras transações.

In [ ]:
transacoes=transacoes["Items"].tolist()

print(transacoes[0])
print(transacoes[1])

['85123A', '71053', '84406B', '84029G', '84029E', '22752', '21730']
['22633', '22632']

Codificação da lista de transações em valores binários.

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
transacoes_codificadas = te.fit(transacoes).transform(transacoes)

print(transacoes_codificadas)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]

Transformação das transações codificadas em um dataframe do pandas para facilitar sua manipulação.

In [ ]:
import pandas as pd

df = pd.DataFrame(transacoes_codificadas, columns=te.columns_)

df

,10002,10080,10120,10123C,10123G,10124A,10124G,10125,10133,10134,...,M,PADS,POST,S,gift_0001_10,gift_0001_20,gift_0001_30,gift_0001_40,gift_0001_50,m
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25895,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25896,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25897,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
25898,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25899,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Geração dos itens frequentes, com suporte mínimo de 0.02.

In [ ]:
from mlxtend.frequent_patterns import apriori

itemsets = apriori(df,min_support=0.02, use_colnames=True)

print("Itemsets frequentes:")
print(itemsets)

Itemsets frequentes:
      support               itemsets
0    0.020193                (15036)
1    0.027181                (20685)
2    0.020541                (20711)
3    0.033668                (20712)
4    0.026023                (20713)
..        ...                    ...
215  0.022471        (85099B, 23203)
216  0.021197         (23301, 23300)
217  0.022896       (85099B, 85099C)
218  0.021042       (85099B, 85099F)
219  0.021197  (22697, 22698, 22699)

[220 rows x 2 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Criação das regras de associação com confiança mínima de 0.5 e transformação das regras geradas em um dataframe para melhorar a apresentação.

In [ ]:
from mlxtend.frequent_patterns import association_rules

regras = association_rules(itemsets, metric="confidence", min_threshold=0.5, num_itemsets=len(df) )
print("Regras de associação")
regras = pd.DataFrame(regras)
regras

Regras de associação

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(20712),(85099B),0.033668,0.082432,0.020772,0.616972,7.484584,1.0,0.017997,2.395566,0.896578,0.217902,0.582562,0.434482
1,(20724),(22356),0.040541,0.029344,0.020309,0.500952,17.071930,1.0,0.019119,1.945018,0.981203,0.409657,0.485866,0.596529
2,(22356),(20724),0.029344,0.040541,0.020309,0.692105,17.071930,1.0,0.019119,3.116193,0.969884,0.409657,0.679096,0.596529
3,(20726),(20725),0.040039,0.062085,0.020541,0.513018,8.263168,1.0,0.018055,1.925976,0.915642,0.251775,0.480783,0.421932
4,(20727),(20725),0.050000,0.062085,0.025019,0.500386,8.059701,1.0,0.021915,1.877280,0.922027,0.287361,0.467314,0.451686
5,(22383),(20725),0.050425,0.062085,0.025598,0.507657,8.176813,1.0,0.022468,1.905003,0.924311,0.294536,0.475067,0.459985
6,(22384),(20725),0.042857,0.062085,0.023668,0.552252,8.895108,1.0,0.021007,2.094740,0.927321,0.291211,0.522614,0.466736
7,(21928),(85099B),0.031506,0.082432,0.021081,0.669118,8.117165,1.0,0.018484,2.773093,0.905327,0.227027,0.639392,0.462428
8,(21929),(85099B),0.033861,0.082432,0.020154,0.595211,7.220592,1.0,0.017363,2.266780,0.891701,0.209639,0.558846,0.419854
9,(21931),(85099B),0.046371,0.082432,0.028301,0.610325,7.403939,1.0,0.024479,2.354698,0.906995,0.281598,0.575317,0.476825
10,(22910),(22086),0.032124,0.045174,0.021429,0.667067,14.766704,1.0,0.019977,2.867926,0.963222,0.383552,0.651316,0.570713
11,(22386),(85099B),0.047529,0.082432,0.032162,0.676686,8.208973,1.0,0.028244,2.838004,0.922004,0.328859,0.647640,0.533425
12,(22411),(85099B),0.045830,0.082432,0.026371,0.575400,6.980264,1.0,0.022593,2.161017,0.897889,0.258810,0.537255,0.447653
13,(22629),(22630),0.035058,0.033205,0.020772,0.592511,17.844227,1.0,0.019608,2.372568,0.978255,0.437398,0.578516,0.609046
14,(22630),(22629),0.033205,0.035058,0.020772,0.625581,17.844227,1.0,0.019608,2.577175,0.976380,0.437398,0.611978,0.609046
15,(22697),(22698),0.040811,0.030965,0.024865,0.609272,19.675976,1.0,0.023601,2.480072,0.989561,0.530041,0.596786,0.706132
16,(22698),(22697),0.030965,0.040811,0.024865,0.802993,19.675976,1.0,0.023601,4.868796,0.979507,0.530041,0.794610,0.706132
17,(22697),(22699),0.040811,0.043243,0.030270,0.741722,17.152318,1.0,0.028505,3.704366,0.981765,0.562814,0.730048,0.720861
18,(22699),(22697),0.043243,0.040811,0.030270,0.700000,17.152318,1.0,0.028505,3.197297,0.984262,0.562814,0.687236,0.720861
19,(22699),(22698),0.043243,0.030965,0.023707,0.548214,17.704177,1.0,0.022368,2.144899,0.986161,0.469419,0.533778,0.656900
20,(22698),(22699),0.030965,0.043243,0.023707,0.765586,17.704177,1.0,0.022368,4.081484,0.973666,0.469419,0.754991,0.656900
21,(22727),(22726),0.041737,0.038726,0.024942,0.597595,15.431412,1.0,0.023326,2.388821,0.975930,0.449235,0.581384,0.620831
22,(22726),(22727),0.038726,0.041737,0.024942,0.644068,15.431412,1.0,0.023326,2.692261,0.972872,0.449235,0.628565,0.620831
23,(23199),(85099B),0.038571,0.082432,0.021429,0.555556,6.739526,1.0,0.018249,2.064527,0.885788,0.215200,0.515628,0.407754
24,(23202),(23203),0.034208,0.048224,0.020000,0.584650,12.123649,1.0,0.018350,2.291504,0.950015,0.320346,0.563605,0.499691
25,(23301),(23300),0.035676,0.029537,0.021197,0.594156,20.115865,1.0,0.020143,2.391222,0.985444,0.481579,0.581804,0.655901
26,(23300),(23301),0.029537,0.035676,0.021197,0.717647,20.115865,1.0,0.020143,3.415315,0.979211,0.481579,0.707201,0.655901
27,(85099C),(85099B),0.036564,0.082432,0.022896,0.626188,7.596379,1.0,0.019882,2.454623,0.901314,0.238248,0.592605,0.451970
28,(85099F),(85099B),0.032046,0.082432,0.021042,0.656627,7.965633,1.0,0.018401,2.672214,0.903412,0.225207,0.625779,0.455948
29,"(22697, 22698)",(22699),0.024865,0.043243,0.021197,0.852484,19.713703,1.0,0.020122,6.485804,0.973479,0.451852,0.845817,0.671332
30,"(22697, 22699)",(22698),0.030270,0.030965,0.021197,0.700255,22.614223,1.0,0.020260,3.232865,0.985615,0.529412,0.690677,0.692397
31,"(22699, 22698)",(22697),0.023707,0.040811,0.021197,0.894137,21.909313,1.0,0.020229,9.060649,0.977531,0.489305,0.889633,0.706766
32,(22697),"(22699, 22698)",0.040811,0.023707,0.021197,0.519395,21.909313,1.0,0.020229,2.031382,0.994963,0.489305,0.507724,0.706766
33,(22698),"(22697, 22699)",0.030965,0.030270,0.021197,0.684539,22.614223,1.0,0.020260,3.074005,0.986322,0.529412,0.674691,0.692397

Criação de um novo dataframe apenas com as colunas mais relevantes para cada regra.

In [ ]:
resumo = regras[['antecedents','consequents','support','confidence']]
resumo

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

       antecedents     consequents   support  confidence
0          (20712)        (85099B)  0.020772    0.616972
1          (20724)         (22356)  0.020309    0.500952
2          (22356)         (20724)  0.020309    0.692105
3          (20726)         (20725)  0.020541    0.513018
4          (20727)         (20725)  0.025019    0.500386
5          (22383)         (20725)  0.025598    0.507657
6          (22384)         (20725)  0.023668    0.552252
7          (21928)        (85099B)  0.021081    0.669118
8          (21929)        (85099B)  0.020154    0.595211
9          (21931)        (85099B)  0.028301    0.610325
10         (22910)         (22086)  0.021429    0.667067
11         (22386)        (85099B)  0.032162    0.676686
12         (22411)        (85099B)  0.026371    0.575400
13         (22629)         (22630)  0.020772    0.592511
14         (22630)         (22629)  0.020772    0.625581
15         (22697)         (22698)  0.024865    0.609272
16         (22698)         (22697)  0.024865    0.802993
17         (22697)         (22699)  0.030270    0.741722
18         (22699)         (22697)  0.030270    0.700000
19         (22699)         (22698)  0.023707    0.548214
20         (22698)         (22699)  0.023707    0.765586
21         (22727)         (22726)  0.024942    0.597595
22         (22726)         (22727)  0.024942    0.644068
23         (23199)        (85099B)  0.021429    0.555556
24         (23202)         (23203)  0.020000    0.584650
25         (23301)         (23300)  0.021197    0.594156
26         (23300)         (23301)  0.021197    0.717647
27        (85099C)        (85099B)  0.022896    0.626188
28        (85099F)        (85099B)  0.021042    0.656627
29  (22697, 22698)         (22699)  0.021197    0.852484
30  (22697, 22699)         (22698)  0.021197    0.700255
31  (22699, 22698)         (22697)  0.021197    0.894137
32         (22697)  (22699, 22698)  0.021197    0.519395
33         (22698)  (22697, 22699)  0.021197    0.684539